package com.example.ofunes.pennypanphone.Entidades;

public enum FragmentOption {
    BREAD, MISCELLANEOUS, SANDWICHBREAD, SANDWICHINGREDIENTS, FINISHSANDWICH, PAYMENTMETHOD, ORDERS, SIGNOFF, UNAUTHORIZED, MARKET
}
